### ISSUE TITLE
Breaks WPGraphql

### ISSUE THREAD

**Issue by HarleySalas** [webdeveducation/wp-graphql-acf-field-groups#1]
Following your Gatsby and Headless WP course;

Upon dragging your plugins in to my project, WPGraphql stops working. Through enabling one at a time, this is the particular one that breaks it.

Any idea what could be causing it? My WPGraphQL is updated to 1.14.0. I realize you may only aim to support your course itself, but I'd hoped to be able to transfer your methodology and workflow to the real world.

The only changes to my plugins are this:

```
WP GraphQL @1.14.0 (originally 1.13.7 from your course)

Cyr-To-Lat @5.5.1
Headless CMS @2.0.1
WooCommerce @7.5.1

```

**Comment by tomphill** [comment]
Hey, @HarleySalas
It seems WPGraphQL v1.14.0 may be the issue here, as it seems to break Gatsby builds in general. Does the issue still persist when you use WPGraphQL v1.13.7? Can you share how WPGraphQL stops working?

**Comment by HarleySalas** [comment]
Unfortunately, downgrading does not solve the issue. 

Essentially, if I enable WP GraphQL ACF Field Groups and go to the GraphiQL IDE in my wp-admin, it just gets stuck on a constant loading spinner. Unresolved Promise; I don't get a 500 error or anything like that in network tab.

The only actual error I get is via Gatsby's `/__graphql` tool, which gives the following error upon querying anything:
```
{
  "errors": [
    {
      "message": "Failed to fetch",
      "stack": "TypeError: Failed to fetch\n    at http://localhost:8000/___graphql/app.js:2:1008689\n    at Generator.next (<anonymous>)\n    at s (http://localhost:8000/___graphql/app.js:2:1008188)\n    at http://localhost:8000/___graphql/app.js:2:1008149\n    at new Promise (<anonymous>)\n    at i.<computed>.r.<computed> [as next] (http://localhost:8000/___graphql/app.js:2:1008101)\n    at http://localhost:8000/___graphql/app.js:2:762233"
    }
  ]
}
```

While not following your course precisely as I'm just skimming through and applying the lessons as I go, I haven't exactly done a lot that I imagine could have caused an issue. None the less, I'll do a fresh WP install with only your plugins from the very beginning and see what happens.

**Comment by tomphill** [comment]
Thank you for the info, @HarleySalas 🙏
I'll see if I can reproduce the issue.

**Comment by HarleySalas** [comment]
Upon creating a new install and only adding your plugins, there was no issue, as it should be.

I then added all of my plugins from my original project back to it to see which one would break it and quite surprisingly, nothing broke it. Easiest solution is for me is to just start over with the new wp install, but I'll see if I can figure it out anyways. I doubt you'd be able to reproduce it. Must be something else, somehow.

**Comment by tomphill** [comment]
Ah, that's very strange! I'll close this issue for now. If you have any other issues please reach out either here or in the Q&A on udemy 😊
